version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: petclinic
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: petclinic
    ports:
      - "5432:5432"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  petclinic:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: postgres
    ports:
      - "8080:8080"
    depends_on:
      - db
