name: CI Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]


jobs:
  env:
    JAVA_VERSION: '17'
    MAVEN_IMAGE: maven:3.8.5-openjdk-17

  checkstyle:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    container:
      image: ${{ env.MAVEN_IMAGE }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle
      - name: Upload Checkstyle Report
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: target/checkstyle-result.xml

  test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    container:
      image: ${{ env.MAVEN_IMAGE }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: mvn test

  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    container:
      image: ${{ env.MAVEN_IMAGE }}
    steps:
      - uses: actions/checkout@v4
      - name: Build App (skip tests)
        run: mvn clean package -DskipTests

  docker-mr:
    if: github.event_name == 'pull_request'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push to MR Repo
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.MR_REPO }}:${{ github.sha }}

  docker-main:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push to Main Repo
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.MAIN_REPO }}:${{ github.sha }}
