name: Spring Petclinic - MAIN repo
on:  
  push:
    branches: main
jobs:
  docker-main:
    runs-on: ubuntu-latest
    steps:
      - name: Get a repo code
        uses: actions/checkout@v5
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Output image name
        run: echo "${{ secrets.MAIN_REPO }}:${{ github.sha }}"
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: "${{ secrets.MAIN_REPO }}:${{ github.sha }}"