name: SPC Build with Github Actions...
on:   
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: checkout - SPC ...
       uses: actions/checkout@v4

     - name: build the codepipeline - with Actions...
       run: mvn package
