name: Spring Pet Clinic Build
on:
  push:
    branches:
        - main
  workflow_dispatch: #manual trigger
jobs:
  maven-name:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v5
       - name: build the code 
         run: mvn package